name: Generate ASCII artwork
on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4      
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y
    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a Dragon .... RAWRRR" >> dragon.txt
    - name: Test file Exists
      run: grep -i "dragon" dragon.txt
    - name: Read Files
      run: cat dragon.txt
    - name: List repo files
      run: ls
